__IPFW_LABEL('S',LSTSTART,0,0)
__IPFW_LABEL('E',LSTEND,0,0)
__IPFW_LABEL('C',CLEAR,0,0)

__IPFW_LABEL('W',WHITE,2,1)
__IPFW_LABEL('R',REJECT,2,1)

__IPFW_LABEL('N',CTRLSTART,0,0)
__IPFW_LABEL('M',CTRLEND,0,0)

__IPFW_LABEL('B',BGP,2,1)
__IPFW_LABEL('H',BGPADD,0,0)
__IPFW_LABEL('J',BGPDEL,0,0)

__IPFW_LABEL('D',DNS,2,0)
__IPFW_LABEL('V',DNSADD,0,0)
__IPFW_LABEL('X',DNSDEL,0,0)

__IPFW_LABEL('U',URL,4,0)
__IPFW_LABEL('Y',URLADD,0,0)
__IPFW_LABEL('Z',URLDEL,0,0)

__IPFW_LABEL('A',CLEARALL,0,0)
__IPFW_LABEL('Q',SQUID,0,0)
