//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.2034
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stRevizor.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("stRevizor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дата загруженного реестра: {0}, отправляю архив реестра на сервер...
        /// </summary>
        internal static string fmtDatelistNew {
            get {
                return ResourceManager.GetString("fmtDatelistNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на истекло количество попыток ({0}) доступа файла {1} на чтение, дальнейшее продолжение невозможно.
        /// </summary>
        internal static string fmtFileBusy {
            get {
                return ResourceManager.GetString("fmtFileBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на попытка {0} -&gt; {1}.
        /// </summary>
        internal static string fmtFileCheck {
            get {
                return ResourceManager.GetString("fmtFileCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на файл {0} отсутствует или не может быть прочитан.
        /// </summary>
        internal static string fmtFileError {
            get {
                return ResourceManager.GetString("fmtFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на файл {0} доступен для обработки.
        /// </summary>
        internal static string fmtFileOk {
            get {
                return ResourceManager.GetString("fmtFileOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не удаеться передать данные серверу. {0} сервер не запущен?.
        /// </summary>
        internal static string fmtSendToError {
            get {
                return ResourceManager.GetString("fmtSendToError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} сервер IP адрес: {1}, тест соединения...
        /// </summary>
        internal static string fmtTestConnection {
            get {
                return ResourceManager.GetString("fmtTestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на XFTP: {0}.
        /// </summary>
        internal static string fmtXFTPAllError {
            get {
                return ResourceManager.GetString("fmtXFTPAllError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на XFTP ({0}): {1}.
        /// </summary>
        internal static string fmtXFTPReciveError {
            get {
                return ResourceManager.GetString("fmtXFTPReciveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ошибка обработки Zip: {0}.
        /// </summary>
        internal static string fmtZipError {
            get {
                return ResourceManager.GetString("fmtZipError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на файл dump.xml не найден по указанному пути: {0}.
        /// </summary>
        internal static string fmtZipFileNotFound {
            get {
                return ResourceManager.GetString("fmtZipFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не удаеться получить автоконфигурацию сервера. stRevizor daemon сервер не запущен?.
        /// </summary>
        internal static string txtAutoconfigError {
            get {
                return ResourceManager.GetString("txtAutoconfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дата загруженного реестра пуста, ошибка в xml файле?.
        /// </summary>
        internal static string txtDatelistEmpty {
            get {
                return ResourceManager.GetString("txtDatelistEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дата загруженного реестра совпадают с текущей, реестр не будет обновлен..
        /// </summary>
        internal static string txtDatelistEquals {
            get {
                return ResourceManager.GetString("txtDatelistEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на нет.
        /// </summary>
        internal static string txtNotSupport {
            get {
                return ResourceManager.GetString("txtNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IP адрес сервера неопределен...
        /// </summary>
        internal static string txtServerIpEmpty {
            get {
                return ResourceManager.GetString("txtServerIpEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на на сервере идет обновление, повторите позднее...
        /// </summary>
        internal static string txtServerIsBusy {
            get {
                return ResourceManager.GetString("txtServerIsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на имя сервера не определено, проверьте настройки...
        /// </summary>
        internal static string txtServNameEmpty {
            get {
                return ResourceManager.GetString("txtServNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на имя FTP пользователя не определено, проверьте настройки...
        /// </summary>
        internal static string txtSrvLoginEmpty {
            get {
                return ResourceManager.GetString("txtSrvLoginEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пароль FTP пользователя не определен, проверьте настройки...
        /// </summary>
        internal static string txtSrvPwdEmpty {
            get {
                return ResourceManager.GetString("txtSrvPwdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на да.
        /// </summary>
        internal static string txtSupport {
            get {
                return ResourceManager.GetString("txtSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на некорректный ip адрес сервера, проверьте настройки...
        /// </summary>
        internal static string txtXFTPBadIpAddress {
            get {
                return ResourceManager.GetString("txtXFTPBadIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на файл dump.xml не найден в Zip архиве.
        /// </summary>
        internal static string txtZipEntryNotFound {
            get {
                return ResourceManager.GetString("txtZipEntryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zip архив не найден.
        /// </summary>
        internal static string txtZipNotFound {
            get {
                return ResourceManager.GetString("txtZipNotFound", resourceCulture);
            }
        }
    }
}
